---
- name: Restart coredns
  ansible.builtin.systemd:
    name: coredns
    state: restarted
    daemon_reload: True

- name: Reload coredns
  ansible.builtin.systemd:
    name: coredns
    state: reloaded
    daemon_reload: True

...
